# Generated by Django 4.1 on 2023-01-05 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_userregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userregistration',
        ),
    ]
