# Generated by Django 4.1 on 2023-01-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_delete_userregistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='admin_password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='email',
            new_name='Username',
        ),
    ]
