# Generated by Django 4.1 on 2023-01-06 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_rename_admin_password_login_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login',
            options={'managed': False},
        ),
    ]
