# Generated by Django 4.1 on 2023-01-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_login_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTab',
            fields=[
                ('pnr_no', models.BigIntegerField(unique=True)),
                ('f_source', models.CharField(blank=True, max_length=10, null=True)),
                ('f_destination', models.CharField(blank=True, max_length=10, null=True)),
                ('seat_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('no_of_tickets', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TICKET_TAB',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='ticket3tab',
            name='flight_no',
        ),
        migrations.RemoveField(
            model_name='ticket3tab',
            name='passport_no',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Ticket3Tab',
        ),
    ]
