# Generated by Django 4.1 on 2023-01-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_tickettab_remove_ticket3tab_flight_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newflightavailable',
            name='No_of_seats',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
