# Generated by Django 4.1 on 2023-01-07 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_contacttab_delete_contact_tickettab_flight_no_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacttab',
            options={'managed': True},
        ),
    ]
