# Generated by Django 4.1 on 2023-01-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_alter_contacttab_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacttabb',
            fields=[
                ('sno', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=20)),
                ('cname', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('ccontent', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Contacttabb',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Contacttab',
        ),
    ]
