# Generated by Django 4.1 on 2023-01-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_contacttabb_delete_contacttab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacttabbb',
            fields=[
                ('sno', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=20)),
                ('cname', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('msg', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Contacttabbb',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Contacttabb',
        ),
    ]
