# Generated by Django 4.1 on 2023-01-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_newpassenger7_ticket_paymentt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newpassenger7',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='bookingstab',
            name='origin',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
