# Generated by Django 4.1 on 2023-01-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_alter_newpassenger7_options_alter_bookingstab_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpassenger7',
            name='f_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='newpassenger7',
            name='pass_email',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='newpassenger7',
            name='passport_no',
            field=models.CharField(default='0000000', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='newpassenger7',
            name='salutation',
            field=models.CharField(blank=True, default='0000000', max_length=10),
        ),
    ]
