# Generated by Django 4.1 on 2023-01-07 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_newpassenger8_delete_newpassenger7_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='flight_no',
            field=models.ForeignKey(blank=True, db_column='flight_no', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='login.newflightavailable'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='passport_no',
            field=models.ForeignKey(blank=True, db_column='passport_no', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='login.newpassenger8'),
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='Ticket___',
        ),
    ]
