# Generated by Django 4.1 on 2023-01-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_ticket_flight_no_ticket_passport_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
