# Generated by Django 4.1 on 2023-01-07 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_ticket_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newpassenger9',
            fields=[
                ('salutation', models.CharField(blank=True, max_length=10, null=True)),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('passport_no', models.CharField(max_length=10)),
                ('pass_number', models.BigAutoField(primary_key=True, serialize=False)),
                ('pass_email', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Newpassenger9',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tticket',
            fields=[
                ('pnr_no', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('f_source', models.CharField(blank=True, max_length=10, null=True)),
                ('f_destination', models.CharField(blank=True, max_length=10, null=True)),
                ('seat_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('no_of_tickets', models.BigIntegerField(blank=True, null=True)),
                ('flight_no', models.ForeignKey(blank=True, db_column='flight_no', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='login.newflightavailable')),
                ('pass_number', models.ForeignKey(blank=True, db_column='pass_number', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='login.newpassenger9')),
            ],
            options={
                'db_table': 'TTicket',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='flight_no',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='passport_no',
        ),
        migrations.DeleteModel(
            name='Newpassenger8',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
