# Generated by Django 4.1 on 2023-01-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_newpassenger9_tticket_remove_ticket_flight_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newflightavailable',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
