# Generated by Django 4.1 on 2023-01-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_alter_newflightavailable_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='newflightavailable',
            name='Businessclass',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newflightavailable',
            name='price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
