# Generated by Django 4.1 on 2023-01-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_remove_newflightavailable_businessclass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingstab',
            name='classtype',
            field=models.CharField(choices=[('Business', 'Business'), ('Economy', 'Economy')], default='economy', max_length=10),
        ),
    ]
