# Generated by Django 4.1 on 2023-01-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_alter_bookingstab_classtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpassenger9',
            name='passport_no',
            field=models.CharField(default='00000', max_length=10),
        ),
    ]
