# Generated by Django 4.1 on 2023-01-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_alter_newpassenger9_passport_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employeebackup',
            fields=[
                ('ssid', models.BigAutoField(primary_key=True, serialize=False)),
                ('emp_dob', models.CharField(blank=True, max_length=10, null=True)),
                ('emp_phone', models.BigIntegerField(blank=True, null=True)),
                ('emp_email', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'employeebackup',
                'managed': True,
            },
        ),
    ]
