# Generated by Django 4.1 on 2023-01-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0027_employeebackup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeebackup',
            name='ssid',
        ),
        migrations.AddField(
            model_name='employeebackup',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
