# Generated by Django 4.1 on 2023-01-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0028_remove_employeebackup_ssid_employeebackup_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employeett',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_dob', models.CharField(blank=True, max_length=10, null=True)),
                ('emp_phone', models.BigIntegerField(blank=True, null=True)),
                ('emp_email', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'EMPLOYEEtt',
                'managed': True,
            },
        ),
        migrations.RenameModel(
            old_name='Employeebackup',
            new_name='Employeedatabackup',
        ),
        migrations.DeleteModel(
            name='Employeet',
        ),
        migrations.AlterModelTable(
            name='employeedatabackup',
            table='EMPLOYEEdataBACKUP',
        ),
    ]
