# Generated by Django 4.1 on 2023-01-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0029_employeett_rename_employeebackup_employeedatabackup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Databackup',
            fields=[
                ('ssid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('emp_dob', models.CharField(blank=True, max_length=10, null=True)),
                ('emp_phone', models.BigIntegerField(blank=True, null=True)),
                ('emp_email', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'DATABACKUP',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employeeblock',
            fields=[
                ('ssid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('emp_dob', models.CharField(blank=True, max_length=10, null=True)),
                ('emp_phone', models.BigIntegerField(blank=True, null=True)),
                ('emp_email', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'EMPLOYEEBLOCK',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Employeedatabackup',
        ),
        migrations.DeleteModel(
            name='Employeett',
        ),
    ]
