# Generated by Django 4.1 on 2023-01-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0030_databackup_employeeblock_delete_employeedatabackup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingstab',
            name='Total_tickets',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
