# Generated by Django 4.1 on 2023-01-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0032_alter_bookingstab_classtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_no', models.BigIntegerField(blank=True, null=True)),
                ('origin', models.CharField(blank=True, max_length=20, null=True)),
                ('destination', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PRICE_HISTORY',
                'managed': True,
            },
        ),
    ]
