# Generated by Django 4.1 on 2023-01-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0033_pricehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricehistory',
            name='id',
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='flight_no',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='pricehistory',
            table='PRICEHISTORY',
        ),
    ]
