# Generated by Django 4.1 on 2023-01-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0034_remove_pricehistory_id_alter_pricehistory_flight_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oldprice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airbus_no', models.CharField(blank=True, max_length=10, null=True)),
                ('origin', models.CharField(blank=True, max_length=20, null=True)),
                ('destination', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'OLDPRICE',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='PriceHistory',
        ),
    ]
