# Generated by Django 4.1 on 2023-01-15 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0035_oldprice_delete_pricehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldprice',
            name='id',
        ),
        migrations.AddField(
            model_name='oldprice',
            name='ID',
            field=models.BigAutoField(default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
