# Generated by Django 4.1 on 2023-01-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0039_newpassenger9view2_delete_newpassenger9view'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewFlightAvailableView',
            fields=[
                ('flight_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('origin', models.CharField(blank=True, max_length=10, null=True)),
                ('destination', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'NEW_FLIGHT_AVAILABLE_VIEW',
                'managed': False,
            },
        ),
    ]
