# Generated by Django 4.1 on 2023-01-17 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0040_newflightavailableview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingstab',
            name='Total_tickets',
        ),
    ]
