# Generated by Django 4.1 on 2023-01-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0041_remove_bookingstab_total_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingstab',
            name='classtype',
            field=models.CharField(choices=[('Business', 'Business'), ('economy', 'economy'), ('Economy', 'Economy'), ('business', 'business')], default='Economy', max_length=10),
        ),
    ]
